name: Build snap

on:
  push:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build

      - name: Show Snapcraft log on build failure
        if: failure()
        run: cat /home/runner/.local/state/snapcraft/log/snapcraft*.log

      - name: Review snap
        uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: "false"

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: corsixth-snap
          path: ${{ steps.build.outputs.snap }}
          retention-days: 7
